### ISSUE TITLE
Criar e implementar arquivo CSV 📑

### ISSUE THREAD

**Issue by e-patricio** [4gu1rr3/T2POO#4]
- [x] Criar arquivo
- [x] Ajustar código e métodos

**Comment by 4gu1rr3** [comment]
OBS.: Vai ter 3 arquivos csv, um de locomotivas, um de vagões e um de trens/composições
Vai ter que ler os de locomotivas e vagões primeiro, criar eles de acordo com o arquivo, adicionar na garagemCarro e então ler o arquivo de trens e criar os trens
*IMPORTANTE: Precisa levar em conta toda a lógica de carga, pesoMáximo, máximo de vagões, disponibilidade na garagem, etc, ou seja, TRATAR ERROS DO ARQUIVO, SE ARQUIVO ESTIVER ERRADO AVISAR USUARIO
